In [35]:
%config IPCompleter.greedy=True

# Adding Libraries...

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Getting Datasets

In [3]:
dataset = pd.read_csv("../data/FirstDataset.csv")
print(dataset)

  Location   Age   Salary Bonus Offered
0    Delhi  44.0  72000.0            No
1   Mumbai  27.0  48000.0           Yes
2   Mumbai  30.0  54000.0            No
3    Delhi  38.0  61000.0            No
4  Chennai  40.0      NaN           Yes
5   Mumbai  35.0  58000.0           Yes
6  Chennai   NaN  52000.0            No
7   Mumbai  48.0  79000.0           Yes
8    Delhi  50.0  83000.0            No
9   Mumbai  37.0  67000.0           Yes


In [4]:
X = dataset.iloc[:, :-1].values
print(X)

[['Delhi' 44.0 72000.0]
 ['Mumbai' 27.0 48000.0]
 ['Mumbai' 30.0 54000.0]
 ['Delhi' 38.0 61000.0]
 ['Chennai' 40.0 nan]
 ['Mumbai' 35.0 58000.0]
 ['Chennai' nan 52000.0]
 ['Mumbai' 48.0 79000.0]
 ['Delhi' 50.0 83000.0]
 ['Mumbai' 37.0 67000.0]]


In [5]:
y = dataset.iloc[:, 3].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['Delhi' 44.0 72000.0]
 ['Mumbai' 27.0 48000.0]
 ['Mumbai' 30.0 54000.0]
 ['Delhi' 38.0 61000.0]
 ['Chennai' 40.0 63777.77777777778]
 ['Mumbai' 35.0 58000.0]
 ['Chennai' 38.77777777777778 52000.0]
 ['Mumbai' 48.0 79000.0]
 ['Delhi' 50.0 83000.0]
 ['Mumbai' 37.0 67000.0]]


In [7]:
dataset = dataset.dropna()
print(dataset)

  Location   Age   Salary Bonus Offered
0    Delhi  44.0  72000.0            No
1   Mumbai  27.0  48000.0           Yes
2   Mumbai  30.0  54000.0            No
3    Delhi  38.0  61000.0            No
5   Mumbai  35.0  58000.0           Yes
7   Mumbai  48.0  79000.0           Yes
8    Delhi  50.0  83000.0            No
9   Mumbai  37.0  67000.0           Yes


In [26]:
dataset = dataset.replace(0, np.nan)
print(dataset)

  Location   Age   Salary Bonus Offered
0    Delhi  44.0  72000.0            No
1   Mumbai  27.0  48000.0           Yes
2   Mumbai  30.0  54000.0            No
3    Delhi  38.0  61000.0            No
4  Chennai  40.0      NaN           Yes
5   Mumbai  35.0  58000.0           Yes
6  Chennai   NaN  52000.0            No
7   Mumbai  48.0  79000.0           Yes
8    Delhi  50.0  83000.0            No
9   Mumbai  37.0  67000.0           Yes


In [30]:
print(dataset.dropna(how="any", subset=["Age"]))

  Location   Age   Salary Bonus Offered
0    Delhi  44.0  72000.0            No
1   Mumbai  27.0  48000.0           Yes
2   Mumbai  30.0  54000.0            No
3    Delhi  38.0  61000.0            No
4  Chennai  40.0      NaN           Yes
5   Mumbai  35.0  58000.0           Yes
7   Mumbai  48.0  79000.0           Yes
8    Delhi  50.0  83000.0            No
9   Mumbai  37.0  67000.0           Yes


In [8]:
print(np.size(dataset, 0))

10


In [9]:
print(np.size(dataset, 1))

4


In [33]:
dataset.iloc[:, :np.size(dataset, 1) -1].values

array([['Delhi', 44.0, 72000.0],
       ['Mumbai', 27.0, 48000.0],
       ['Mumbai', 30.0, 54000.0],
       ['Delhi', 38.0, 61000.0],
       ['Chennai', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Chennai', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Delhi', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [34]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
y = labelEncoder.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 30.0 54000.0]
 [0.0 1.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 nan]
 [0.0 0.0 1.0 35.0 58000.0]
 [1.0 0.0 0.0 nan 52000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 37.0 67000.0]]


In [38]:
from sklearn.preprocessing import MinMaxScaler
norm = MinMaxScaler()
X = norm.fit_transform(X)
print(X)


[[0.         1.         0.         0.73913043 0.68571429]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         1.         0.13043478 0.17142857]
 [0.         1.         0.         0.47826087 0.37142857]
 [1.         0.         0.         0.56521739        nan]
 [0.         0.         1.         0.34782609 0.28571429]
 [1.         0.         0.                nan 0.11428571]
 [0.         0.         1.         0.91304348 0.88571429]
 [0.         1.         0.         1.         1.        ]
 [0.         0.         1.         0.43478261 0.54285714]]


In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)

[[1.         0.         0.         0.56521739        nan]
 [0.         0.         1.         0.43478261 0.54285714]
 [0.         0.         1.         0.         0.        ]
 [1.         0.         0.                nan 0.11428571]
 [0.         0.         1.         0.91304348 0.88571429]
 [0.         1.         0.         0.47826087 0.37142857]
 [0.         1.         0.         0.73913043 0.68571429]
 [0.         0.         1.         0.34782609 0.28571429]]


In [11]:
dataset = pd.read_csv("ContainsNil.csv")
dataset = dataset.replace("Nil", 0)
print(dataset)

  Location Age Salary Bonus Offered
0    Delhi  44  72000            No
1   Mumbai  27  48000           Yes
2   Mumbai  30  54000            No
3    Delhi  38  61000            No
4  Chennai  40      0           Yes
5   Mumbai  35  58000           Yes
6  Chennai   0  52000            No
7   Mumbai  48  79000           Yes
8    Delhi  50  83000            No
9   Mumbai  37  67000           Yes


In [7]:
print(X)

[[1 44.0 72000.0]
 [2 27.0 48000.0]
 [2 30.0 54000.0]
 [1 38.0 61000.0]
 [0 40.0 nan]
 [2 35.0 58000.0]
 [0 nan 52000.0]
 [2 48.0 79000.0]
 [1 50.0 83000.0]
 [2 37.0 67000.0]]
