In [208]:
import pandas as pd
import numpy as np


In [209]:
dataset = pd.read_csv("Social_Network_Ads.csv")
print(dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [210]:
X = dataset.iloc[:, 2:4].values
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [211]:
y = dataset.iloc[:, 4]
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64


In [212]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)

[[-0.25843537 -1.39436183]
 [ 0.4054353   2.40368541]
 [-1.30166071  0.60933238]
 [-0.25843537 -1.36445595]
 [ 0.97446731  0.63923827]
 [-1.68101539 -0.58690297]
 [-0.82746738  2.37377953]
 [ 0.21575797  0.10093236]
 [-1.01714471  0.63923827]
 [ 0.4054353   0.34017943]
 [ 0.1209193   0.19065001]
 [ 0.31059664 -0.49718532]
 [-0.06875803  0.07102647]
 [-1.68101539 -0.97567946]
 [ 0.68995131 -1.09530299]
 [-0.92230604 -0.28784413]
 [-0.1635967   1.6859442 ]
 [ 0.87962864 -1.15511476]
 [-0.63779004 -1.51398537]
 [ 0.4054353   0.19065001]
 [ 0.4054353   0.63923827]
 [ 1.35382198 -0.91586769]
 [ 0.68995131 -1.39436183]
 [-1.11198338  0.37008531]
 [ 0.1209193  -0.79624416]
 [ 0.02608063  1.29716771]
 [ 1.16414465 -1.4541736 ]
 [-0.63779004 -0.31775002]
 [-0.06875803  2.25415599]
 [-0.06875803 -0.40746767]
 [-0.4481127   1.32707359]
 [-0.92230604 -0.28784413]
 [-1.30166071 -1.24483241]
 [-0.1635967  -0.1682206 ]
 [ 0.02608063  1.32707359]
 [-0.35327404  1.29716771]
 [ 0.31059664  0.07102647]
 

In [213]:
from sklearn.ensemble import RandomForestClassifier
randomClassifier = RandomForestClassifier(n_estimators = 300, criterion='entropy', n_jobs=32, bootstrap=False) 
randomClassifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=32, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [214]:
print(X_test)
y_pred = randomClassifier.predict(X_test)

[[ 0.59511264 -0.88596181]
 [ 0.87962864 -0.55699709]
 [-1.11198338  1.47660301]
 [ 0.1209193   0.25046178]
 [-1.58617672  0.10093236]
 [ 0.87962864  1.14763829]
 [-0.1635967   2.25415599]
 [ 0.21575797  1.14763829]
 [ 0.21575797  0.19065001]
 [ 1.82801532 -1.06539711]
 [ 1.44866065  2.22425011]
 [-0.25843537 -0.3476559 ]
 [-0.25843537 -0.88596181]
 [ 0.1209193   0.31027354]
 [-1.01714471 -0.31775002]
 [ 1.54349932  1.05792064]
 [ 0.21575797  0.07102647]
 [ 2.11253132 -0.67662062]
 [-0.1635967  -0.43737355]
 [ 1.54349932 -1.2747383 ]
 [-1.49133805  0.37008531]
 [ 0.21575797 -0.28784413]
 [-0.35327404  1.38688536]
 [-0.4481127   0.01121471]
 [-0.54295137 -1.51398537]
 [-0.06875803  0.34017943]
 [-0.25843537 -1.24483241]
 [ 0.50027397  1.29716771]
 [-0.06875803 -0.3476559 ]
 [ 0.97446731 -1.18502065]
 [ 1.06930598 -0.88596181]
 [-1.77585405  0.48970885]
 [ 1.35382198  0.63923827]
 [-0.06875803 -0.46727943]
 [-1.01714471 -1.54389125]
 [-0.35327404 -1.30464418]
 [-0.06875803  0.31027354]
 

In [215]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

cm1 = confusion_matrix(y_test, y_pred_random)
print(cm1)

[[44  4]
 [ 3 29]]
[[34 14]
 [23  9]]


In [216]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
print(acc)

acc1 = accuracy_score(y_test, y_pred_random)
print(acc1)

0.9125
0.5375
